# Generated by Django 2.0.13 on 2019-05-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20190514_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificaton_type',
            new_name='notification_type',
        ),
    ]
