# Generated by Django 2.0.13 on 2019-05-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20190504_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='creator',
        ),
    ]
